version: 1.0
provider:
  name: openfaas
  gateway: https://openfaas-ingress-rberrelleza.cloud.okteto.net
functions:
  hello:
    lang: node12
    handler: ./hello
    image: registry.cloud.okteto.net/rberrelleza/openfaas-nodejs

